name: first-job-by-Adarsh
on: workflow-dispatch
jobs: 
  first-job:
  runs-on: ubuntu-latest
  steps:
    - name: say-hello
      run: echo "hello,Adarsh!"
    - name: say-goobye
      run: echo "goodbye,struggle" 
  
